@extends('layouts.master')
@section('title')
    Home
@endsection
@include('layouts.header')
@section('content')
@include('layouts.banner')
@include('layouts.services')
@include('layouts.contact')
@include('layouts.footerr')
@endsection